* Moved to https://codeberg.org/nibbula/lisp-mode-snippets

Some small shabby snippets for Common Lisp using the Emacs yasnippets package.

I haven't included everything in Common Lisp, only the things that are hard
for me to remember or very common and long.

INSTALL:

  Check out into or link to: [[file:~/.emacs.d/snippets/lisp-mode/]]

  You also may want/need to load funcs.el which are functions used when
  expanding certain snippets. Perhaps it should be in a .yas-setup.el file,
  but the documentation says TODO, so I haven't put it in there. You can just
  load it from your .emacs or something.

USE:

  Generally, there are two styles of expansion, one where you've already typed
  the starting paren, and one where the expansion will put it in for you.

- Starting paren already typed:

#+BEGIN_SRC common-lisp
  (defclass<TAB>
#+END_SRC

will expand to:

#+BEGIN_SRC common-lisp
  (defclass name (superclasses) ...)
#+END_SRC

- Starting paren included:

#+BEGIN_SRC common-lisp
  (defclass foo (bar)
    (slot<TAB>)
    (:documentation "A foo for you."))
#+END_SRC

will put the paren in for you:

#+BEGIN_SRC common-lisp
  (defclass foo (bar)
    ((slot-name :initarg slot-name :accessor ...))
    (:documentation "A foo for you."))
#+END_SRC

Enjoy!
